### ISSUE TITLE
v1.1.3 installs LICENSE to incorrect location

### ISSUE THREAD

**Issue by wimglenn** [halcy/blurhash-python#1]
the dist on PyPI installs custom LICENSE file into incorrect location (env root)
it should install to the metadata subdir i.e. `site-packages/blurhash-1.1.3.dist-info/`
unfortunately I can not fix the installer in a PR because v1.1.3 seems untagged/not pushed on github

**Comment by halcy** [comment]
hm, oops, must have forgotten to push

I'm considering changing it back, in any case - this was an experiment, and I believe it has run its course. I will fix it when I next update Mastodon.py, which I'll likely be doing next weekend, if that's quick enough for you?

**Comment by wimglenn** [comment]
No problem for me, just an FYI. Note that test.pypi.org is a helpful resource for package metadata experiments (the test index is mutable).

**Comment by halcy** [comment]
Fixed by not having the custom license.
