### ISSUE TITLE
Can we call this pure python implementation from Google Cloud Functions?

### ISSUE THREAD

**Issue by aytunch** [halcy/blurhash-python#2]
There is one more Pyhton implementation of BlurHash which is not pure Python(It uses C code)
I want to make a HTTP request function in Cloud Functions which will run this Python library and encode an Image and return a blurhash string. Is it possible? [Are these guidelines by google enough?](https://cloud.google.com/functions/docs/quickstart-python#create_a_function) Do we need special imports and so on?

Thanks

**Comment by halcy** [comment]
pppprobably? the package depends on absolutely nothing, not even numpy, the dependencies that exist are only for the tests. Do feel free to give it a try. Closing this, as it isn't really an issue.
